name: Go package

on: [push]

jobs:
  go-tools:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.24.6'

      - name: go fmt
        run: make gofmt

      - name: gofumpt
        run: |
          git fetch origin main --depth 1
          make gofumpt

      - name: go vet
        run: make govet

      - name: staticcheck
        run: make staticcheck

      - name: tfplugindocs
        run: make docs-check

      - name: compliance
        run: make compliance-check
