name: Go package

on: [push]

jobs:
  go-tools:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.20'

      - name: go fmt
        run: make gofmt

      - name: go vet
        run: make govet

      - name: tfplugindocs
        run: make docs-check

      - name: compliance
        run: make compliance-check
